### ISSUE TITLE
Fix keyboards coming up for math inputs on iPadOS 13

### ISSUE THREAD

**Issue by corimcelwain** [desmosinc/mathquill#140]
**browser**: Safari on iPadOS 13

### Steps to Trigger Behavior

1. Go to an activity on teacher.desmos.com that has a math input using an iPad with updated OS. 
2. Open a screen with math input
3. Focus in the math input 

### Expected Behavior
Our scientific keypad appears. 

### Actual Behavior
Nothing! The scientific keypad and native keypad do not show up. 

Note from Eric in slack: 
> Hi Jason!

> I'm Charles from the Safari and WebKit engineering teams at Apple.

> We'd like to ask you to make a small change to your wonderful website desmos.com.

> Desmos's math field editor on your calculator pages creates hidden textareas for text entry. We'd like to request adding an inputmode="none" attribute to these invisible textarea elements when you have your own virtual keyboard on screen. This indicates that your web page implements your own keyboard input control.

> Thank you! Please let us know if you have any questions!

> Best,
Charles

**Comment by jwmerrill** [comment]
I think this may be fixed. Closing because I don't think this will be addressed by code inside mathquill in any case.
