### ISSUE TITLE
Publish build to NPM

### ISSUE THREAD

**Issue by esotrope** [desmosinc/mathquill#145]
Are you guys able to create an NPM user and update your CI config to publish the builds to the public NPM repository?
This would greatly improve the installation and update process for your library.
Currently, I need to download the source for the version I want, build and copy-paste the artifacts into my project to get things rolling.

Thanks & cheers!

**Comment by leonfrischauf** [comment]
yep, this would also be especially important to us!

**Comment by jwmerrill** [comment]
We don't plan to do this in `desmosinc/mathquill`. I recommend using `mathquill/mathquill` instead. We're working on getting our changes merged upstream (see e.g. https://github.com/mathquill/mathquill/pull/947).

**Comment by mon-jai** [comment]
Any news?

**Comment by filipesmedeiros** [comment]
Hello! I love Desmos! Thank you so much for everything. But I am sort of confused. Why have this project open source (and public) if there is basically no way of using it? Or at least no documented way. Thank you!
